set (FRAMEWORK_SRC_DIR  ${TICOS_FRAMEWORK_PATH}/src)
set (PLATFORM_DIR       ${TICOS_FRAMEWORK_PATH}/platforms/${TICOS_PLATFORM})

aux_source_directory (${FRAMEWORK_SRC_DIR}/core         CORE_SRCS)
aux_source_directory (${PLATFORM_DIR}/src               PLATFORM_SRCS)
if (TICOS_USE_FREERTOS)
aux_source_directory (${FRAMEWORK_SRC_DIR}/os/freertos  OS_SRCS)
endif ()
set (FRAMEWORK_SRCS ${PLATFORM_SRCS} ${OS_SRCS} ${CORE_SRCS})
set (FRAMEWORK_INCS ${PLATFORM_DIR}/inc ${FRAMEWORK_SRC_DIR})

if (DEFINED TICOS_CLOUD_SDK)
message (STATUS "Looking for TICOS_SDK_PATH")
if (DEFINED ENV{TICOS_SDK_PATH})
set (TICOS_SDK_SRC_DIR $ENV{TICOS_SDK_PATH}/src)
message (STATUS "Found TICOS_SDK_PATH from env: $ENV{TICOS_SDK_PATH}")
elseif (EXISTS ${TICOS_FRAMEWORK_PATH}/../${TICOS_CLOUD_SDK})
set (TICOS_SDK_SRC_DIR ${TICOS_FRAMEWORK_PATH}/../${TICOS_CLOUD_SDK}/src)
message (STATUS "Found TICOS_SDK_PATH from the parent direcroty")
elseif (EXISTS $ENV{HOME}/.ticos/packages/${TICOS_CLOUD_SDK})
set (TICOS_SDK_SRC_DIR $ENV{HOME}/.ticos/packages/${TICOS_CLOUD_SDK}/src)
message (STATUS "Found TICOS_SDK_PATH from the default ticos direcroty")
else ()
message (FATAL_ERROR "TICOS_SDK_PATH not found")
endif ()
aux_source_directory (${TICOS_SDK_SRC_DIR}      TICOS_SDK_SRCS)
set (TICOS_SDK_INCS ${TICOS_SDK_SRC_DIR})
endif ()
